<a href="https://colab.research.google.com/github/GiselleNidhoggr/BestLearnCodes/blob/main/Giselle_Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Atividades - Python para Data Science - FIT

Instrutor:  ```adson.nogueira@fit-tecnologia.org.br```

Aluna:  ```Giselle de Oliveira Almeida```


## Exercícios Dia Um


1. Importe NumPy como `np`

In [ ]:
import numpy as np

2. Crie um array com 10 zeros 

In [ ]:
array=np.zeros(10)
array

In [ ]:
type(array)

3. Crie um array com 10 'uns'

In [ ]:
array_ones=np.ones(10)
array_ones

4. Crie um array com 10 'cincos'

In [ ]:
array_five=array_ones*5
array_five

5. Crie um vetor de números inteiros de 10 ate 50

In [ ]:
np.arange(10,51,10) #com número inteiro

In [ ]:
#float
#np.linspace(10,50,5)

6. Crie um vetor com o numeros pares de 10 até 50

In [ ]:
np.arange(10,51,2)

7. Crie uma matriz $3 \times 3$ com os valores de 0 até 8

In [ ]:
#matriz=[[0,1,2],[3,4,5],[6,7,8]]
matriz=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(matriz)

8. Crie uma matriz identidade $7 \times 7$

In [ ]:
np.eye(7)

9. Use numpy para gerar um número aleatório entre 0 e 1

In [ ]:
#np.random.randint(0,2) #gera um número INTEIRO aleatório entre 0 e 1
np.random.rand(1) #gera um número FLOAT aleatório entre 0 e 1

10. Use o numpy para gerar 25 números aleatório de distribuição normal padrão (gaussiana com média $\mu = 0$ e desvio padrão $\sigma = 1$)

In [ ]:
0 + 1 * np.random.randn(5, 5) #método 1, matriz 5x5

In [ ]:
np.random.randn(25) #método 2, matriz linear. Pode ser aplicado reshape

11. Crie a matrix abaixo

```python
array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])
```

In [ ]:
#método 1
matriz1=np.arange(0.01,1.01,0.01)
matriz1=matriz1.reshape(10,10)
print(matriz1)

In [ ]:
#método 2
b= np.linspace(0.01, 1.00, 100)
b=b.reshape(10,10)
b=b.round(2)
print(b)

12. Crie um array de 20 elementos igualmente espaçados entre 0 e 1:

In [ ]:
b= np.linspace(0, 1, 20)
b=b.reshape(4,5) #pra ficar bonito
print(b)

13. Dada a matrix abaixo,

```python
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

obtenha as seguintes matrizes por indexação e se necessário, reshape:


```python
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [ ]:
c= np.linspace(1,25, 25)
c=c.reshape(5,5) #pra ficar bonito
print(c)

* 
```python
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```


In [ ]:
c[2:5,1:]

* 
```python
array([[ 2],
       [ 7],
       [12]])
```


In [ ]:
c[:3,1]


* 
```python
array([21, 22, 23, 24, 25])
```


In [ ]:
c[4]

* 
```python
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [ ]:
c[3:5,:]

14. Some todos os valores da matriz

In [ ]:
c.sum()

15. Some todas as colunas da matriz

In [ ]:
c.sum(axis=0)

16. Calcule o desvio padrão por coluna

In [ ]:
c.std(axis=0)

## Exercícios Dia Dois

Nestes exercícios vamos utilizar os dados de salários da cidade de São Francisco, [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) do site do [Kaggle](https://www.kaggle.com). 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

1. Importe pandas como pd.

In [ ]:
import pandas as pd

2. Leia o arquivo Salaries.csv e salve as informações no DataFrame sal.

In [ ]:
sal=pd.read_csv('/content/drive/MyDrive/Arquivos para Python/Salaries.csv')

3. Verifique os primeiros registros de sal.

In [ ]:
sal.head()

4. Use o método `info()` para descobrir o número de registros.

In [ ]:
sal.info()

5. Qual é a média de BasePay?

In [ ]:
sal['BasePay'].mean()

6. Qual é o maior salário em OvertimePay no dataset?

In [ ]:
sal['OvertimePay'].max()

7. Qual a profissão (JobTitle) de Courtney T Mcelrath?

In [ ]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

8. Quanto ela recebe incluindo os benefícios (TotalPayBenefits)?

In [ ]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

9. Qual a pessoa mais bem paga incluindo os benefícios?

In [ ]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].max()]['EmployeeName']

10. Qual a pessoa com o pior pagamento incluindo os benefícios?

In [ ]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()]['EmployeeName']

11. Qual e média da base salárial (BasePay) de todos os funcionários no período de 2011-2014?

In [ ]:
sal.groupby('Year')['BasePay'].mean()

12. Quantas profissões diferente há nessa base de dados?

In [ ]:
sal['JobTitle'].nunique() #profissões por tipo único

13. Quais são as 5 profissões mais comuns?

In [ ]:
sal['JobTitle'].value_counts().head(5) #profissões mais comuns (conta todos os valores da profissão)

14. Quantas profissões tinham apenas uma pessoa no ano de 2014?

In [ ]:
sum(sal[sal['Year'] == 2014]['JobTitle'].value_counts()==1)

15. Quantas pessoas tem a palavra 'Chief' na sua profissão (jobTitle)?

In [ ]:
#'adson' in 'adson nogueira alves' DICA

sum(sal['JobTitle'].apply(lambda s : 'chief' in str(s).lower().split()))

16. Há correlação (correlation) entre o tamanho do nome da profissão e o salário?

In [ ]:
#df[['TotalPayBenefits', 'JobTitle']].corr() FALHOU

In [ ]:
df['title_len'] = df['JobTitle'].apply(len)

In [ ]:
df[['TotalPayBenefits', 'title_len']].corr() #AGORA FOI